# Generated by Django 5.1.1 on 2025-09-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_category_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='estimation',
            new_name='score',
        ),
    ]
